apiVersion: v1
kind: Service
metadata:
  name: filtering-sorting-service
spec:
  selector:
    app: filtering-sorting-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: criteria-based-search-service
spec:
  selector:
    app: criteria-based-search-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  selector:
    app: user-management-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: hotel-search-service
spec:
  selector:
    app: hotel-search-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: naming-server
spec:
  selector:
    app: naming-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb2
spec:
  selector:
    app: mongodb2
  ports:
    - protocol: TCP
      port: 27019
      targetPort: 27017
  type: ClusterIP
